name: deploy

on: 
  workflow_dispatch:
    inputs:
      commit-msg:
        description: 'コミットメッセージ'
        required: true
        default: '新PRIME実装'
    
jobs:
  job_1:
    name: make json then upload
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install dependencies
      run: |
        cd vue-relic
        npm ci

    - name: Build
      run: npm run build

    - name: Commit file
      run: |
        git config --local user.name '${{ secrets.SECRET_NAME }}'
        git config --local user.email '${{ secrets.SECRET_EMAIL }}'
        git add .
        git commit -m "${{ github.event.inputs.commit-msg }}"
        git push origin master