name: deploy

on: 
  workflow_dispatch:
    inputs:
      commit-msg:
        description: 'コミットメッセージ'
        required: true
        default: '新PRIME実装'
    
jobs:
  job_1:
    name: deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        cd relic
        yarn install

    - name: Build
      run: |
        cd relic
        yarn build

    - name: Commit file
      run: |
        git config --local user.name '${{ secrets.SECRET_NAME }}'
        git config --local user.email '${{ secrets.SECRET_EMAIL }}'
        git add .
        git commit -m "${{ github.event.inputs.commit-msg }}"
        git push origin master